apiVersion: apps/v1
kind: Deployment
metadata:
  name: t2-frontend
  namespace: prod
  labels:
    app: t2-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t2-frontend
  template:
    metadata:
      labels:
        app: t2-frontend
    spec:
      containers:
      - name: t2-frontend
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
          - name: BASE_URL
            value: http://backend:9000
            
---
apiVersion: v1
kind: Service
metadata:
  name: t2-frontend
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: t2-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
