apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-policy
  namespace: default  
spec:
  podSelector:
    matchLabels:
      app: hello-node
  ingress:
  - from:
    - ipBlock:
        cidr: 10.233.0.0/16
        except:
        - 10.233.90.0/32
    ports:
    - protocol: TCP 
      port: 6443
      
